name: Update Data

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  schedule:
    # Run at 9:00 every day
    - cron: "0 9 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip3 install requests
          pip3 install matplotlib
      
      - name: Run script
        run: python3 update.py
      
      - name: Commit data
        run: |
          git config user.name "Update Bot"
          
          git add .
          git commit -m "Updated data"
          git push
